# This file was generated by GoReleaser. DO NOT EDIT.
cask "paracell" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "5ec8267a2e40449f1586d5f145ac8cdf29688c461caccb626c3c04cc458504bc"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "074db19c363c044397aaaf7367bc88312189be1bef20453e00f0f0ca1feec8e1"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "86bc781410f997f86c00448504f1cc3e48a05c03adc9ff27286c0b99086c3024"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eed932e291c16f488973ff55222c3729e9d991f2e763cd9c348884f81ad145e7"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_linux_arm64.tar.gz"
    end
  end

  name "paracell"
  desc "Create isolated per-issue development cells from a project repo"
  homepage "https://github.com/hgsg11/paradev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paracell"

  # No zap stanza required

end
