# This file was generated by GoReleaser. DO NOT EDIT.
cask "paracell" do
  version "0.1.14"

  on_macos do
    on_intel do
      sha256 "f9cad84e464350c951b359cd465dbb159871406dfac15022aa2b06dafb01eaf5"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ccd480426ef2119e47a26d828c5db9b99d0f6dd5329c55f5b3834cdee0fafe79"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7514e244b19b507917ced21675e1c2fecd28c4fb6ff2e04caa1cdcd5f3bda46e"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef68ff355f45a06dad1b3e30579e448b43970eda3fab1fca1a2226dc05c0dcba"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_linux_arm64.tar.gz"
    end
  end

  name "paracell"
  desc "Create isolated per-issue development cells from a project repo"
  homepage "https://github.com/hgsg11/paradev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paracell"

  # No zap stanza required

end
