# This file was generated by GoReleaser. DO NOT EDIT.
cask "paracell" do
  version "0.1.26"

  on_macos do
    on_intel do
      sha256 "e3ef9b38bd7dfd6a776995aea861c24eb79811d78d7ecc185842dab19715fe6d"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6eed550e01d4e4a5c9eff586a4b32e1411d65808101446db7b7cb6f4a7c56781"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9c3feaf83a23058d169b94132459ba908a618f63c9bf3dd57eb57dc8c6a363f"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "64d17ece68b78b81dbef790028a4e9861c9d3aff54e0331d5ac31fcdd5d65c15"
      url "https://github.com/hgsg11/paracell/releases/download/v#{version}/paracell_linux_arm64.tar.gz"
    end
  end

  name "paracell"
  desc "Create isolated per-issue development cells from a project repo"
  homepage "https://github.com/hgsg11/paradev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paracell"

  # No zap stanza required

end
